// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43hHl8zEdjfThodAYBUx4EICr1YN3qp8',
    appId: '1:796953336754:web:6614e842b30937f12da2ab',
    messagingSenderId: '796953336754',
    projectId: 'votewise',
    authDomain: 'votewise.firebaseapp.com',
    storageBucket: 'votewise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkoqGactGAP8t04646-6kkZIkL-fPQgj8',
    appId: '1:796953336754:android:b57216199b7581de2da2ab',
    messagingSenderId: '796953336754',
    projectId: 'votewise',
    storageBucket: 'votewise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowOluIArGIkDhZarPnq3VpAG2k2dB4tU',
    appId: '1:796953336754:ios:f87e6817c7b531612da2ab',
    messagingSenderId: '796953336754',
    projectId: 'votewise',
    storageBucket: 'votewise.appspot.com',
    iosClientId: '796953336754-fksp3enh5avp7mt28t8vcj9k1o5jt1go.apps.googleusercontent.com',
    iosBundleId: 'com.example.votewiseiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowOluIArGIkDhZarPnq3VpAG2k2dB4tU',
    appId: '1:796953336754:ios:f87e6817c7b531612da2ab',
    messagingSenderId: '796953336754',
    projectId: 'votewise',
    storageBucket: 'votewise.appspot.com',
    iosClientId: '796953336754-fksp3enh5avp7mt28t8vcj9k1o5jt1go.apps.googleusercontent.com',
    iosBundleId: 'com.example.votewiseiq',
  );
}
